server:
  port: 80

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
   com.itlike: debug
  path: "D:/test/test.log"

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.itlike.pojo
  configuration:
    map-underscore-to-camel-case: true
